toolID: 269
kickFlag: false
banFlag: true
shoutFlag: true

# set to true for MCBans global bans. Be sure to follow their
# guidelines:
# http://wiki.mcbans.com/display/MCBans/Honeypot+Guidelines
# MCBans is not functional atm.
globalBan: false

banLog: true
banLogLocation: true
logPath: plugins/Candybag/candybag.log

candybagKickBanSender: '[CandyBag]'
honeypotBanReason: Destroyed block in a candy bag.
candybagBanReason: Placed block in a candy bag.
honeypotKickMessage: '[CandyBag] You have been caught destroying a block in a candy bag.'
candybagKickMessage: '[CandyBag] You have been caught placing a block in a candy bag.'

# can be used in lieu of "offensePoints", is a simpler concept.
# Basically counts each block break as one infraction so, for
# example, you can require that 3 honeypot blocks must be broken
# before action is taken.
#offenseCount: 0

# how may offense points until they are banned
#offensePoints: 3

# ability to make some blocks worth more or less points. Helpful
# if you're honeypotting a region that is a honeypot statue,
# for example, so you could ignore dirt/snow blocks, etc.
# This example makes iron/gold/diamond blocks worth 3 points
# and grass,snow and ice blocks worth 0
#offensePointMap:
#  "56": 3
#  "41": 3
#  "42": 3
#  "2": 0
#  "78": 0
#  "79": 0

# This defines which permission system is used. Vault and WEPIF
# (WEPIF is built into WorldEdit) are preferred, they both provide
# a nice interface to all other permission systems. If you don't have
# or don't want to use either of those, there is some native support
# for a few other permission systems that you can use. These are
# checked in the order they are listed for existence, and the
# first one to match is used.
permissions:
  - vault
  - wepif
  - pex
  - superperms
  - ops
