name: CandyBag
main: com.argo.bukkit.honeypot.Honeypot
version: 1.2
author: Argomirr,morganm,dog.big,dwdcweb
softdepend: [WorldEdit]
commands:
 honeypot:
  description: Enables Op's to create honeypots by right clicking a block with a wooden axe.
  usage: /<command>
  aliases: [hp]
